export const GET_PENDING_ORDERS = 'GET_PENDING_ORDERS';
export const GET_ALL_ORDERS= 'GET_ALL_ORDERS';
export const GET_CANCEL_ORDERS = 'GET_CANCEL_ORDERS';
export const GET_CLOSED_ORDERS= 'GET_CLOSED_ORDERS';
export const GET_DISPATCHED_ORDERS = 'GET_DISPATCHED_ORDERS';
export const GET_ORDER_DETAIL = 'GET_ORDER_DETAIL';
export const ORDER_STATE_CHANGE = 'ORDER_STATE_CHANGE';
export const CLEAN_ORDER = 'CLEAN_ORDER';